### ISSUE TITLE
> Can't we just use this? There are no problems with it. If you're going to ignore someone's hard work then I'm not going to work with you then. You ignore people's ideas sometimes.

### ISSUE THREAD

**Issue by hello-smile6** [The-Catalyst-Browser-Project/get-catalyst#3]
> Can't we just use this? There are no problems with it. If you're going to ignore someone's hard work then I'm not going to work with you then. You ignore people's ideas sometimes.

I am BUSY with like 5 other notifications right now!!!

_Originally posted by @JaydenDev in https://github.com/The-Catalyst-Browser-Project/get-catalyst/issues/1#issuecomment-1004507664_

@JaydenDev I have 1610 notifications right now. Get used to it.

**Comment by JaydenDev** [comment]
@hello-smile6 because of how many projects with people complaining about SOMEONE who broke them?

**Comment by JaydenDev** [comment]
@hello-smile6 continue to make issues instead of commenting on the posts will result in consequences.

**Comment by webdev03** [comment]
because the posts are locked, thats why

**Comment by JaydenDev** [comment]
@webdev03 for a reason maybe?
